version: '3.8'
services:
  airflow:
    build: .
    platform: linux/arm64
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__FERNET_KEY: utGhZJoL9d5KumS2pm3_mmhQfPwCRDpR2z-qFhuH7Ms=
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-arm64
      PYTHONPATH: /opt/airflow/src
      _PIP_ADDITIONAL_REQUIREMENTS: pyspark great_expectations scikit-learn
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow:/opt/airflow
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./airflow/logs:/opt/airflow/logs
      - ./jars:/opt/airflow/jars
    ports:
      - "8080:8080"
    restart: always
    command: bash -c "airflow db migrate && airflow webserver"
  airflow-scheduler:
    build: .
    platform: linux/arm64
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-arm64
      AIRFLOW__CORE__FERNET_KEY: utGhZJoL9d5KumS2pm3_mmhQfPwCRDpR2z-qFhuH7Ms=
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      PYTHONPATH: /opt/airflow/src
      _PIP_ADDITIONAL_REQUIREMENTS: pyspark great_expectations scikit-learn
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow:/opt/airflow
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./airflow/logs:/opt/airflow/logs
      - ./jars:/opt/airflow/jars
    restart: always
    command: bash -c "airflow db migrate && airflow scheduler"
